import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useAccount} from "wagmi";
import {useEffect, useRef, useState} from "react";
import {BigNumber, utils} from "ethers";
import {IDXClient} from "../components/ceramic/IDXClient";
import {getSeedFromAddress} from "../components/util";
const idxClient = new IDXClient()

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected , isConnected } = useAccount()
  const [did,setDID] = useState(null);
  const [refreshCount,setRefreshCount] = useState(0)

  useEffect(()=>{
    if(isConnected){
      const seed = getSeedFromAddress(address)
      idxClient.getJsDID(seed).then(async (did) => {
        console.log(did)
        // @ts-ignore
        setDID(did)
        const v = await idxClient.readUserInfo()
        console.log(v)
      })
    }
  },[refreshCount])

  return (
    <div className={styles.container}>
      <Head>
        <title>DIDStorage</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {
          isDisconnected && <h1 className={styles.title}>
            Please connect  <a href="">Wallet </a>{'first '}
          </h1>
        }
        {
          isConnected && <h1 className={styles.title}>
            Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
            <a href="https://nextjs.org">Next.js!</a>
          </h1>
        }

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://rainbowkit.com" className={styles.card}>
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
