import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useAccount} from "wagmi";
import {useEffect} from "react";
import {BigNumber, utils} from "ethers";
import {IDXClient} from "../components/ceramic/IDXClient";
const idxClient = new IDXClient()

const Home: NextPage = () => {

  const { address, isConnecting, isDisconnected , isConnected } = useAccount()

  useEffect(()=>{
    if(isConnected){
      // @ts-ignore
      const hash = utils.keccak256(address.toString());
      console.log(hash)
      // @ts-ignore
      const array = hash
          // @ts-ignore
          .replace('0x', '')
          // @ts-ignore
          .match(/.{2}/g)
          .map((hexNoPrefix) => BigNumber.from('0x' + hexNoPrefix).toNumber())
      console.log(array)
      const seed = JSON.parse(JSON.stringify(array));
      idxClient.getJsDID(seed).then((did) => {
        console.log(did)

        interface  UserInfo{
          name : string,
          sex: string,
          location:string,
          website:string,
          description:string
        }
        const kv = {
          "name":"test",
          "files":[]
        }
        // @ts-ignore
        idxClient.writeUserInfo(kv).then(async r => {
          const v = await idxClient.readUserInfo()
          console.log(v)
        })

        const kv1 = {
          "name":"test",
          "files":["1"]
        }
        // @ts-ignore
        idxClient.writeUserInfo(kv1).then(async r => {
          const v = await idxClient.readUserInfo()
          console.log(v)
        })
      })
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>DIDStorage</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {
          isDisconnected && <h1 className={styles.title}>
            Please connect  <a href="">Wallet </a>{'first '}
          </h1>
        }
        {
          isConnected && <h1 className={styles.title}>
            Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
            <a href="https://nextjs.org">Next.js!</a>
          </h1>
        }

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://rainbowkit.com" className={styles.card}>
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
